/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.universidad.vista;

/**
 *
 * @author Mauro
 */



import com.mycompany.universidad.modelo.PlanDeEstudio.*;
import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Arrays;

public class PlanDeEstudioGUI extends JFrame {
    private List<PlanDeEstudio> listaPlanes;
    private DefaultListModel<String> modeloLista;
    private JList<String> listaVisual;
    private JButton btnCancelar;

    public PlanDeEstudioGUI() {
        setTitle("Planes de Estudio");
        setSize(600, 500);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        // Panel principal con fondo oscuro
        JPanel panelPrincipal = new JPanel(new BorderLayout());
        panelPrincipal.setBackground(new Color(50, 50, 100));
        panelPrincipal.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));

        // Panel de título
        JPanel panelTitulo = new JPanel();
        panelTitulo.setBackground(new Color(50, 50, 100));
        JLabel lblTitulo = new JLabel("Planes de Estudio", SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 20));
        lblTitulo.setForeground(Color.WHITE);
        panelTitulo.add(lblTitulo);

        // Inicializar lista de planes
        listaPlanes = Arrays.asList(
            new PlanA("Plan A"),
            new PlanB("Plan B"),
            new PlanC("Plan C"),
            new PlanD("Plan D"),
            new PlanE("Plan E")
        );

        // Lista visual de planes
        modeloLista = new DefaultListModel<>();
        listaVisual = new JList<>(modeloLista);
        JScrollPane scrollPane = new JScrollPane(listaVisual);

        // Mostrar los planes cargados
        actualizarListaVisual();

        // Botón de Cancelar
        btnCancelar = crearBoton("Cancelar");
        btnCancelar.addActionListener(e -> dispose());

        // Panel para el botón de cancelar
        JPanel panelBotones = new JPanel();
        panelBotones.setBackground(new Color(50, 50, 100));
        panelBotones.add(btnCancelar);

        // Agregar componentes al frame
        panelPrincipal.add(panelTitulo, BorderLayout.NORTH);
        panelPrincipal.add(scrollPane, BorderLayout.CENTER);
        panelPrincipal.add(panelBotones, BorderLayout.SOUTH); // Se añade el botón de cancelar

        add(panelPrincipal);

        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void actualizarListaVisual() {
        modeloLista.clear();
        for (PlanDeEstudio plan : listaPlanes) {
            modeloLista.addElement(plan.toString()); // Usa el toString() de cada plan
        }
    }

    private JButton crearBoton(String texto) {
        JButton boton = new JButton(texto);
        boton.setFont(new Font("Arial", Font.BOLD, 14));
        boton.setBackground(new Color(100, 100, 200));
        boton.setForeground(Color.WHITE);
        boton.setFocusPainted(false);
        boton.setPreferredSize(new Dimension(150, 40)); 
        return boton;
    }

    



    














    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
